title: Soraia Gomes Teixeira
author: Bruno Santos
description:

collections:
  works:
    sort_by: order


docs_list_title: ACME Documentation
docs:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

date_format: "%b %-d, %Y"
